// ============================================================
//  Duet — vendor image assets into the extension
// ============================================================
// Regenerates, from npm packages (no network calls at runtime):
//   extension/vendor/avatars/av-NN.svg   — DiceBear "adventurer" portraits
//   extension/vendor/twemoji/<cp>.svg    — only the emoji Duet's UI uses
//   extension/vendor/twemoji-set.js      — which emoji are bundled
//   extension/vendor/CREDITS.txt         — attribution (CC BY 4.0 artwork)
//
// Usage:  cd tools && npm install && npm run vendor-assets
//
// Emoji are collected from string literals in content.js and popup.js, so
// adding an emoji to a picker and re-running this picks it up. Anything not
// bundled (e.g. an emoji typed into chat) renders as the system emoji.

import { readFileSync, writeFileSync, mkdirSync, rmSync, copyFileSync, existsSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createAvatar } from "@dicebear/core";
import { adventurer } from "@dicebear/collection";

const require = createRequire(import.meta.url);
const HERE = dirname(fileURLToPath(import.meta.url));
const EXT = join(HERE, "..", "extension");
const OUT = join(EXT, "vendor");

// ── Avatars ─────────────────────────────────────────────────
// Index = the NN in "av:NN" codes stored in meta.emoji. Never reorder:
// existing users' saved avatars point at these indices.
const AVATARS = [
  ["Mochi", "ffd5dc,ff9eb8"], ["Pepper", "ffdfbf,ffb37b"], ["Suki", "ffe5b4,f4c542"], ["Felix", "c8e6c9,7bc99c"],
  ["Luna", "b6e3f4,7ec8e3"], ["Nico", "c0aede,9d7adf"], ["Sasha", "f8bbd0,e57ea3"], ["Kira", "d1d4f9,8b9cf2"],
  ["Theo", "ffc89a,ff7e5f"], ["Ivy", "a8e6cf,5ec27a"], ["Rio", "ffeaa7,fdcb6e"], ["Juno", "fab1a0,e17055"],
  ["Zara", "fd79a8,d63384"], ["Atlas", "74b9ff,0984e3"], ["Wren", "a29bfe,6c5ce7"], ["Hugo", "fdcb6e,f39c12"],
  ["Mila", "e17055,c0392b"], ["Bo", "00b894,00897b"], ["Indigo", "ff7675,d63031"], ["Soren", "fd79a8,e84393"],
  ["Nova", "55efc4,00b894"], ["Cleo", "81ecec,00cec9"], ["Otis", "ffeaa7,fab1a0"], ["Vesper", "dfe6e9,b2bec3"]
];

rmSync(join(OUT, "avatars"), { recursive: true, force: true });
mkdirSync(join(OUT, "avatars"), { recursive: true });
AVATARS.forEach(([seed, bg], i) => {
  // Same options the old api.dicebear.com/9.x URLs used, so faces don't change.
  const svg = createAvatar(adventurer, {
    seed,
    backgroundColor: bg.split(","),
    backgroundType: ["gradientLinear"]
  }).toString();
  writeFileSync(join(OUT, "avatars", `av-${String(i).padStart(2, "0")}.svg`), svg);
});

// ── Twemoji ─────────────────────────────────────────────────
// Same matcher content.js uses to decide what to swap for an image.
const EMOJI_RE = /\p{Emoji_Presentation}|\p{Emoji}️/gu;

// Twemoji file naming: hex code points joined by "-", with U+FE0F dropped
// unless the sequence contains a ZWJ (mirrors twemoji's own lookup). Must
// match twemojiFile() in content.js.
function twemojiFile(emoji) {
  const text = emoji.includes("‍") ? emoji : emoji.replace(/️/g, "");
  return Array.from(text, ch => ch.codePointAt(0).toString(16)).join("-");
}

const sources = ["content.js", "popup.js"].map(f => readFileSync(join(EXT, f), "utf8"));
// Plus the status/system glyphs built at runtime from string pieces.
const extra = ["👋", "💬", "💞", "⏳", "⚠️", "🎬", "📺", "👤", "♥️"];
const found = new Set(extra);
for (const src of sources) {
  // Whole file, comments included: an extra file or two is cheaper than a
  // string-literal parser that trips over apostrophes.
  for (const [m] of src.matchAll(EMOJI_RE)) found.add(m);
}

const twemojiDir = dirname(require.resolve("@twemoji/svg/package.json"));
rmSync(join(OUT, "twemoji"), { recursive: true, force: true });
mkdirSync(join(OUT, "twemoji"), { recursive: true });
const bundled = [];
const missing = [];
for (const emoji of [...found].sort()) {
  const file = twemojiFile(emoji);
  const src = join(twemojiDir, `${file}.svg`);
  if (!existsSync(src)) { missing.push(`${emoji} (${file})`); continue; }
  copyFileSync(src, join(OUT, "twemoji", `${file}.svg`));
  bundled.push(file);
}
const uniq = [...new Set(bundled)].sort();

writeFileSync(join(OUT, "twemoji-set.js"),
`// Generated by tools/vendor-assets.mjs — do not edit by hand.
// Twemoji files bundled under vendor/twemoji/. Others render as system emoji.
globalThis.DUET_TWEMOJI = new Set(${JSON.stringify(uniq)});
`);

writeFileSync(join(OUT, "CREDITS.txt"),
`Third-party artwork bundled with Duet
=====================================

Emoji graphics (vendor/twemoji/)
  Twemoji — Copyright Twitter, Inc. and other contributors (jdecked/twemoji)
  Licensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/
  Packaged via @twemoji/svg 15.0.0 (MIT).

Avatar portraits (vendor/avatars/)
  "Adventurer" by Lisa Wischofsky, via DiceBear (https://www.dicebear.com)
  Licensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/
  Generated with @dicebear/core + @dicebear/collection 9.4.2 (MIT).
`);

console.log(`avatars: ${AVATARS.length}, twemoji: ${uniq.length} files` +
  (missing.length ? `, not in Twemoji (system emoji): ${missing.join(" ")}` : ""));
